with(obj_pawn) 
    instance_destroy();
with(obj_rook) 
    instance_destroy();
with(obj_knight) 
    instance_destroy();
with(obj_bishop) 
    instance_destroy();
with(obj_queen) 
    instance_destroy();
with(obj_king) 
    instance_destroy();
global.isPieceClicked=false;
global.currentPiece=noone;
global.currentCell=noone;
